### ISSUE TITLE
Stripe PHP Library missing error

### ISSUE THREAD

**Issue by papercrate** [backdrop-contrib/stripe_checkout#11] opened 2017-10-27 23:39 UTC
After installing the API and Checkout module and configuring them, I am still getting a Stripe PHP Library missing error on the Backdrop status report. I have downloaded the master file and installed it in the module/libraries/stripe location as instructed but the error remains and the module is unable to connect when testing. Would be interested to know if anyone else has this issue or knows of a solution.

**Comment by laryn** [comment] 2017-10-28 02:23
@papercrate I saw [your comments over on the stripe module](https://github.com/backdrop-contrib/stripe/issues/7) as well. As @jenlampton mentioned, we're midstream in bundling the Stripe library in the module but it doesn't have a formal release yet. If you are using the latest releases, you should put the library in `/libraries/stripe` (not in `/modules/libraries/stripe`).

**Comment by papercrate** [comment] 2017-10-28 04:55
@laryn thanks for the follow up. Sorry for cross-posting. I wasn't sure which code it made sense to comment in. I had tried that directory as well but still had the same error. Curious...

**Comment by jenlampton** [comment] 2017-12-03 18:21
@papercrate ~~I'm unable to reproduce this error on the 1.x-2.x branch of the Stripe module. Can you post a link here to which version you are currently using? This problem may be easy enough to resolve by issuing a new release... but it would be good to confirm that will actually fix the problem first.~~

edit: oh, never mind. It looks like the error is coming from stripe_checkout, and I haven't tested one that yet :)

**Comment by laryn** [comment] 2020-08-05 22:29
Closing this issue as this module is no longer maintained. Stripe development is now centering around
the [Stripe](https://github.com/backdrop-contrib/stripe) module, including the bundled `webform_stripe` functionality.

**Closed as completed by laryn** 2020-08-05 22:29 UTC
